jenkins_jobs:
 jenkins_host: http://47.93.232.166:8083
 jobs:
  - git_branch: master
    git_type: bitbucket
    job_name: t1_build
    job_token: 123456
    job_param: ssh_server=t1.xianbei.cc&port=1818&ssh_user=root&ssh_pwd=Wangzikai123
    job_type: buildWithParameters
  - git_branch: master
    git_type: github
    job_name: pocket_task
    job_token: 123456
    job_type: build

